import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import { AuthProvider } from "@/Context/Auth";
import ToasterClient from "@/components/ToasterClient";
import ReduxProvider from "./redux/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gill Mart | Online Shopping for Everything You Need",
  description: "Generated by Usman Gill",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* ✅ Wrap entire app with ReduxProvider */}
        <ReduxProvider>

          {/* Your existing providers */}
          <AuthProvider>
            <Layout>
              <ToasterClient />
              {children}
            </Layout>
          </AuthProvider>

        </ReduxProvider>

      </body>
    </html>
  );
}
